name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip

    - name: Ensure pip >= v25.1
      run: python -m pip install "pip >= 25.1"

    - name: Install ypywidgets in dev mode
      run: pip install --group dev -e .

    - name: Check types
      run: mypy src

    - name: Run tests
      if: ${{ !((matrix.python-version == '3.13') && (matrix.os == 'ubuntu-latest')) }}
      run: pytest ./tests -v --color=yes

    - name: Run code coverage
      if: ${{ (matrix.python-version == '3.13') && (matrix.os == 'ubuntu-latest') }}
      run: |
        coverage run -m pytest tests
        coverage report --fail-under=100
